// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_cEr4edWPV6NrpJg_p4NYjK1JhNapEzg',
    appId: '1:737189062779:web:8b372cc5880d7955969ade',
    messagingSenderId: '737189062779',
    projectId: 'license-training-v1',
    authDomain: 'license-training-v1.firebaseapp.com',
    storageBucket: 'license-training-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZr7UqFqs6PHXcqk9QiCPvGGI2bgM6mq0',
    appId: '1:737189062779:android:615cd58bee171a27969ade',
    messagingSenderId: '737189062779',
    projectId: 'license-training-v1',
    storageBucket: 'license-training-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKsZfGhztxG7VIe6ELAFvz1hLjedrtZgc',
    appId: '1:737189062779:ios:6b97132866755c29969ade',
    messagingSenderId: '737189062779',
    projectId: 'license-training-v1',
    storageBucket: 'license-training-v1.appspot.com',
    iosBundleId: 'com.example.licensetrainining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKsZfGhztxG7VIe6ELAFvz1hLjedrtZgc',
    appId: '1:737189062779:ios:459b263a82fbd3be969ade',
    messagingSenderId: '737189062779',
    projectId: 'license-training-v1',
    storageBucket: 'license-training-v1.appspot.com',
    iosBundleId: 'com.example.licensetrainining.RunnerTests',
  );
}
