// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu4alKylFVwEnYYRn9i-7KG4j89iD8UQc',
    appId: '1:562117995723:web:7fcb153876797fdb55bf4e',
    messagingSenderId: '562117995723',
    projectId: 'licensetraning',
    authDomain: 'licensetraning.firebaseapp.com',
    storageBucket: 'licensetraning.appspot.com',
    measurementId: 'G-ZY27WCTN38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwpG6voXpEzxHbRyFTBOdWxePAgWAr3Y',
    appId: '1:562117995723:android:0983d647411a38e255bf4e',
    messagingSenderId: '562117995723',
    projectId: 'licensetraning',
    storageBucket: 'licensetraning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm122ucNxNCnZaIJE4EYNnx9GZNHWl7BA',
    appId: '1:562117995723:ios:cef99aa1233995d155bf4e',
    messagingSenderId: '562117995723',
    projectId: 'licensetraning',
    storageBucket: 'licensetraning.appspot.com',
    iosBundleId: 'com.example.licensetrainining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm122ucNxNCnZaIJE4EYNnx9GZNHWl7BA',
    appId: '1:562117995723:ios:7967cc7a304c29f555bf4e',
    messagingSenderId: '562117995723',
    projectId: 'licensetraning',
    storageBucket: 'licensetraning.appspot.com',
    iosBundleId: 'com.example.licensetrainining.RunnerTests',
  );
}
